src/Entity/Order.php
<?php

namespace App\Entity;

use App\Repository\OrderRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\UX\Turbo\Attribute\Broadcast;

#[ORM\Entity(repositoryClass: OrderRepository::class)]
#[ORM\Table(name: '`order`')]
#[Broadcast]
class Order
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $orderNumber = null;

    #[ORM\Column(length: 50)]
    private ?string $totalAmount = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $orderDate = null;

    #[ORM\OneToMany(mappedBy: 'orderId', targetEntity: OrderDetails::class)]
    private Collection $OrderDetails;

    #[ORM\Column]
    private ?int $totalQuantity = null;

    #[ORM\Column(length: 50)]
    private ?string $status = null;

    public function __construct()
    {
        $this->OrderDetails = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrderNumber(): ?string
    {
        return $this->orderNumber;
    }

    public function setOrderNumber(string $orderNumber): static
    {
        $this->orderNumber = $orderNumber;

        return $this;
    }

    public function getTotalAmount(): ?string
    {
        return $this->totalAmount;
    }

    public function setTotalAmount(string $totalAmount): static
    {
        $this->totalAmount = $totalAmount;

        return $this;
    }

    public function getOrderDate(): ?\DateTimeInterface
    {
        return $this->orderDate;
    }

    public function setOrderDate(\DateTimeInterface $orderDate): static
    {
        $this->orderDate = $orderDate;

        return $this;
    }

    /**
     * @return Collection<int, OrderDetails>
     */
    public function getOrderDetails(): Collection
    {
        return $this->OrderDetails;
    }

    public function addOrderDetail(OrderDetails $orderDetail): static
    {
        if (!$this->OrderDetails->contains($orderDetail)) {
            $this->OrderDetails->add($orderDetail);
            $orderDetail->setOrderId($this);
        }

        return $this;
    }

    public function removeOrderDetail(OrderDetails $orderDetail): static
    {
        if ($this->OrderDetails->removeElement($orderDetail)) {
            // set the owning side to null (unless already changed)
            if ($orderDetail->getOrderId() === $this) {
                $orderDetail->setOrderId(null);
            }
        }

        return $this;
    }

    public function getTotalQuantity(): ?int
    {
        return $this->totalQuantity;
    }

    public function setTotalQuantity(int $totalQuantity): static
    {
        $this->totalQuantity = $totalQuantity;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }
}

templates/_cart.html.twig
<div class="flex-block-cart" id="goods-quick-stats2">
    <div class="cart-container">
        <div class="cart-header">
            <h2 class="cart-title">Кошик</h2>
            <div class="cart-items-count">
                <span class="counter-text">Товарів:</span>
                <span class="counter">{{ goodsQuantity }}</span>
            </div>
        </div>
        <div class="cart-items">
            <ul>
                {% for goods in cart %}
                    <li class="cart-item">
                        <img src="{{ goods.image }}" alt="{{ goods.name }}" class="product-image">
                        <div class="product-details-cart">
                            <h3 class="product-title-cart">{{ goods.name }}</h3>
                            <form class="delete-form" action="{{ path('app_clear_cart', {id: goods.id}) }}" method="post">
                                <button type="submit"><i class='bx bxs-trash'></i></button>
                            </form>
                            <p class="product-attribute">Розмір: {{ goods.sizes }}</p>
                            <turbo-frame id="turbo-quantity-cart-{{goods.id}}-{{goods.sizeId}}">
                                {% for message in app.flashes('error-cart') %}
                                    <script>document.body.style.overflow = 'hidden';</script>
                                    <div class="error-no-goods" onclick="this.remove(); document.body.style.overflow = 'auto';">
                                        <div class="error-popup">
                                            <div class="error-icon">
                                                <i class='bx bx-error-alt'></i>
                                            </div>
                                            <h5 class="ops">Упс!</h5>
                                            <div class="error-message">{{ message }}</div>
                                            <div class="end-error-message">Закрити</div>
                                        </div>
                                    </div>
                                {% endfor %}
                                {% for messageQuantity in app.flashes('error-quantity-cart') %}
                                    <script>document.body.style.overflow = 'hidden';</script>
                                    <div class="error-no-goods" onclick="this.remove(); document.body.style.overflow = 'auto';">
                                        <div class="error-popup">
                                            <div class="error-icon">
                                                <i class='bx bx-error-alt'></i>
                                            </div>
                                            <h5 class="ops">Упс!</h5>
                                            <div class="error-message">{{ messageQuantity }}</div>
                                            <div class="end-error-message">Закрити</div>
                                        </div>
                                    </div>
                                {% endfor %}
                                <div class="quantity-panel">
                                    <form action="{{ path('app_update_cart', {action: 'decrease'}) }}" method="post">
                                        <input type="hidden" name="goods_id" value="{{ goods.id }}">
                                        <input type="hidden" name="size_id" value="{{ goods.sizeId }}">
                                        <button type="submit" class="quantity-button">-</button>
                                    </form>
                                    <span class="quantity-span" id="goods-quick-stats2">{{ goods.quantity }}</span>
                                    <form action="{{ path('app_update_cart', {action: 'increase'}) }}" method="post">
                                        <input type="hidden" name="goods_id" value="{{ goods.id }}">
                                        <input type="hidden" name="size_id" value="{{ goods.sizeId }}">
                                        <button type="submit" class="quantity-button">+</button>
                                    </form>
                                </div>
                            </turbo-frame>
                            <p class="product-price-cart">{{ goods.price * goods.quantity }} USD</p>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="cart-summary">
        <div class="total-amount">
            <h4 class="total-text">Загальна сума:</h4>
            <h4 class="total-price">{{ totalAmounts }} USD</h4>
        </div>
        <form action="{{ path('app_place_order')}}" method="post">
            <button class="order-button" type="submit">Перейти до оформлення</button>
        </form>
        <div class="description-cart-order">
            <span>CПОСОБИ ОПЛАТИ</span>
            <br>
            <img class="svg-visa-mastercard" src="{{ asset('svg/visa-mastercard-new.svg') }}" alt="svg-visa-mastercard">
            <p class="description-cart-order-p">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
            <p class="description-cart-order-p">Type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        </div>
    </div>
</div>

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block stylesheets %}
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous"><link >
        <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/boxicons@2.0.7/css/boxicons.min.css">
        <link rel="stylesheet" type="text/css" href="{{ asset('js/slick-1.8.1/slick/slick.css') }}"/>
        <link rel="stylesheet" type="text/css" href="{{ asset('js/slick-1.8.1/slick/slick-theme.css') }}"/>
        <link href=" {{ asset('main.css') }} " rel="stylesheet">

    {% endblock %}

</head>
<body>
<div class="">
    <!-- Header -->
    {% block header %}{% endblock %}

    <!-- Main -->
    {% block body %}
    {% endblock %}

    <!-- Footer -->
    {% block footer %}{% endblock %}

    {% block javascripts %}
        {{ encore_entry_script_tags('app') }}
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/efdad892b6.js" crossorigin="anonymous"></script>
    {% endblock %}
</div>
</body>
</html>

templates/cart.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {% include 'header.html.twig' %}
{% endblock %}

{% block body %}
    <div class="main-cart-container mt-4">
        {% if cart is empty %}
            <div class="no-cart">
                <h2 class="">Ваш кошик порожній</h2>
                <p class="">Якщо ви впевнені, що сюди щось додавалось, спробуйте увійти
                    <br>
                    до свого облікового запису і подивитись там ;)</p>
                <div class="">
                    <form class="" action="#">
                        <button type="submit">Увійти</button>
                    </form>
                </div>
                <a href="{{ path('app_main')}}">Або продовжити купування</a>
            </div>
        {% else %}

            {% include '_cart.html.twig' %}

        {% endif %}
    </div>

{% endblock %}

templates/femaleGoods.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {% include 'header.html.twig' %}
{% endblock %}

{% block body %}
    {% if type is not null %}
        <h5 class="title-goods">{{ type }}</h5>
    {% else %}
        <h5 class="title-goods">ДЛЯ НЕЇ</h5>
    {% endif %}
    <div class="container-fluids">
        <button id="toggle-filters">Ф<br>І<br>Л<br>Ь<br>Т<br>Е<br>Р</button>
        <div class="sidebar" id="sidebar">
            <div class="filters" id="filters">
                <div class="filter-group">
                    <ul>
                        <li class="li-a-menu">
                            <a class="a-menu-filter">Одяг</a>
                            <ul class="filter-list">
                                <li><a href="/female/t-shirt">Футболка</a></li>
                                <li>Кофти</li>
                                <li>Худі</li>
                                <li><a href="/female/Pants">Штани</a></li>
                                <li><a href="/female/outerwear">Пальто</a></li>
                            </ul>
                        </li>
                        <li class="li-a-menu">
                            <a class="a-menu-filter">Взуття</a>
                            <ul class="filter-list">
                                <li>Кросівки</li>
                                <li>Кеди</li>
                            </ul>
                        </li>
                        <li class="li-a-menu">
                            <a class="a-menu-filter">Аксесуари</a>
                            <ul class="filter-list">
                                <li>Шкарпетки</li>
                                <li>Кепки</li>
                                <li>Шапка</li>
                                <li>Окуляри</li>
                                <li>Сумки</li>
                                <li>Браслети</li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="content" id="content">
            <div class="goods">
                <div class="sorting">
                    <div class="sort-price">
                        <div class="sort">
                            <label class="sort-label" for="sort-select" onclick="toggleSortOptions()">Сортувати за:</label>
                            <div class="sort-options" id="sort-options">
                                <div class="sort-option">
                                    <input type="radio" id="sort-default" name="sort-option" value="default" checked>
                                    <label for="sort-default">За замовчуванням</label>
                                </div>
                                <div class="sort-option">
                                    <input type="radio" id="sort-asc" name="sort-option" value="price-asc" >
                                    <label for="sort-asc">Зростанням ціни</label>
                                </div>
                                <div class="sort-option">
                                    <input type="radio" id="sort-desc" name="sort-option" value="price-desc" >
                                    <label for="sort-desc">Спаданням ціни</label>
                                </div>
                                <button class="apply-button" onclick="applySorting()">Застосувати</button>
                            </div>
                        </div>
                    </div>
                    <turbo-frame id="turbo-sort-price">
                        <div class="sort-price">
                            <div class="sort">
                                <label class="sort-label" id="price-toggle" onclick="togglePriceOptions()">Ціна</label>
                            </div>
                            <form method="post">
                                <div class="price-options" id="price-options" style="display: none;">
                                    <input type="text" name="min_price" id="min-price" placeholder="Від" value="{{ minPrice }}">
                                    <input type="text" name="max_price" id="max-price" placeholder="До" value="{{ maxPrice }}">
                                    <button class="price-button" type="submit">Показати</button>
                                </div>
                            </form>
                        </div>
                    </turbo-frame>

                </div>
                <div class="goods-list-container">
                    <turbo-frame id="goods-list-turbo-{{ paginator.currentPage }}" target="_top">
                        <div class="row">
                            {% for goods in paginator.getCurrentPageResults() %}
                                <div class="col col-md-3">
                                    <a class="linkANon" href="{{ path('app_goodsPage', {'slug': goods.slug }) }}">
                                        <div class="good-card" data-id="{{ goods.id }}">
                                            <img class="default-image" src="{{ goods.image }}" alt="{{ goods.name }}">
                                            {% set hoverImage = goods.getGoodsImages()|first %}
                                            {% if hoverImage %}
                                                <img class="hover-image" src="{{ asset(hoverImage.getImages()) }}" alt="Goods Image">
                                            {% endif %}
                                            <h4 class="product-title">{{ goods.name }}</h4>
                                            <p class="price">{{ goods.price }} USD</p>
                                        </div>
                                    </a>
                                </div>
                            {% endfor %}

                            {% if paginator.hasNextPage %}
                                <turbo-frame
                                        id="goods-list-turbo-{{ paginator.nextPage }}"
                                        src="{{ pagerfanta_page_url(paginator, paginator.NextPage) }}"
                                        loading="lazy"
                                        target="_top">
                                </turbo-frame>
                            {% endif %}
                        </div>
                    </turbo-frame>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{{ asset('js/menuFilter.js') }}"></script>
    <script src="{{ asset('js/femaleGoodsSort.js') }}"></script>
    <script>
    </script>
{% endblock %}

{% block footer %}
    {% include 'footer.html.twig' %}
{% endblock %}

templates/footer.html.twig
{% extends 'base.html.twig' %}

{% block footer %}
    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-md-4">
                    <h4>Контакти</h4>
                    <ul class="contact-info">
                        <li><i class="fas fa-phone-alt"></i>Телефон: (111) 111-1111</li>
                        <li><i class="fas fa-envelope"></i>Email: <a href="mailto:info@yourstore.com">info@yourstore.com</a></li>
                        <li><i class="fas fa-map-marker-alt"></i>Адреса: 123 Main St. Anytown, USA</li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h4>Навігація</h4>
                    <ul class="list-unstyled">
                        <li><a href="#">Головна</a></li>
                        <li><a href="#">Про нас</a></li>
                        <li><a href="#">Каталог</a></li>
                        <li><a href="#">Контакти</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <h4>Підписатися</h4>
                    <p>Підписуйтесь на нашу розсилку, щоб отримувати спеціальні пропозиції та оновлення:</p>
                    <form>
                        <div class="form-group">
                            <input type="email" class="form-control" placeholder="Email">
                        </div>
                        <button type="submit" class="btn-footer btn-primary">Підписатися</button>
                    </form>
                </div>
                <div class="col-md-2">
                    <h4>Соцмережі</h4>
                    <div class="social-media-icons">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-youtube"></i></a>
                        <a href="#"><i class="fab fa-tiktok"></i></a>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <p class="text-center">&copy; 2023 Всі права захищені | Назва магазину</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock %}

templates/goodsFormBuy.html.twig
<turbo-frame id="buy-button-turbo">
    <div class="product-sizes">
        <p>Розмір</p>
        {% for goodsSize in goods.getGoodsSizes %}
            {% if goodsSize.getSizeId is not null %}
                {% set size = goodsSize.getSizeId.getSize %}
                {% set quantity = goodsSize.getQuantity %}
                <div {% if quantity == 0 %}class="size-pill-null" {% elseif quantity > 0 %}class="size-pill" {% endif %} data-size-id="{{ goodsSize.getSizeId.id }}">{{ size }}</div>
            {% endif %}
        {% endfor %}
    </div>
    <script>addSizePillEventListeners();</script>
    <form class="add-to-cart" action="{{ path('app_to_cart') }}" method="post" onsubmit="return validateSizeSelection()">
        <input type="hidden" name="goods_id" value="{{ goods.id }}">
        <input type="hidden" name="size_id" id="size_id" value="">
        {% for message in app.flashes('error') %}
            <script>document.body.style.overflow = 'hidden';</script>
            <div class="error-no-goods" onclick="this.remove(); document.body.style.overflow = 'auto';">
                <div class="error-popup">
                    <div class="error-icon">
                        <i class='bx bx-error-alt'></i>
                    </div>
                    <h5 class="ops">Упс!</h5>
                    <div class="error-message">{{ message }}</div>
                    <div class="end-error-message">Закрити</div>
                </div>
            </div>
        {% endfor %}
        {% if hasAvailableSizes %}
            <button type="submit" class="add-to-cart-btn" id="add-to-cart-btn"><i class='bx bx-shopping-bag'></i> Додати у кошик</button>
        {% else %}
            <button type="submit" class="add-to-cart-btn-null" disabled>Товару немає в наявності</button>
        {% endif %}
    </form>
</turbo-frame>

templates/order_history.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {% include 'header.html.twig' %}
{% endblock %}

{% block body %}
    <h4 class="title-order">Замовлення</h4>
    <div class="container-fluid order-container-fluid">
        <div class="order-filter">
            <nav>
                <label class="filter-label active" >Всі</label>
                <label class="filter-label">Виконані</label>
                <label class="filter-label">Скасовані</label>
                <label class="filter-label">Поточні</label>
            </nav>
        </div>
        <div class="main-order-block">
            <div class="order-menu">
                <div class="order-header-item-num">Номер замовлення</div>
                <div class="order-header-item-date">Дата</div>
                <div class="order-header-item-quantity">Кількість</div>
                <div class="order-header-item-price">Загальна ціна</div>
                <div class="order-header-item-status">Статус</div>
            </div>
            {% for order in orders|reverse %}
                <div class="order-block" onclick="toggleOrderDetails(this)">
                    <div class="order-header">
                        <div class="num-date-order">
                            <p class="order-number">№ {{ order.orderNumber }}</p>
                            <p class="order-date">{{ order.orderDate|date('d F Y H:i') }}</p>
                            <p class="quantity-order-all">{{ order.totalQuantity }}</p>
                            <p class="order-total">{{ order.totalAmount }} USD</p>
                            <p class="status-order">{{ order.status }}</p>
                            <i class="toggle-arrow fas fa-chevron-up"></i>
                        </div>
                    </div>
                    <div class="order-details">
                        <ul class="goods-list">
                            {% for orderDetail in order.orderDetails %}
                                <li class="goods-item">
                                    {% set goods = orderDetail.goodsId %}
                                    <a href="{{ path('app_goodsPage', {'slug': goods.slug }) }}">
                                        <div class="product-thumbnail">
                                            <img src="{{ goods.image }}" alt="{{ goods.name }}">
                                        </div>
                                    </a>
                                    <div class="goods-details">
                                        <div>
                                            <a class="linkANon" href="{{ path('app_goodsPage', {'slug': goods.slug }) }}">
                                                <p class="goods-name">{{ goods.name }}</p>
                                                <p class="goods-code">Код товару: {{ goods.code }}</p>
                                            </a>
                                        </div>
                                        <div class="detail-order">
                                            <p>Розмір: {{ orderDetail.size}}</p>
                                            <p class="quantity-order">Кількість: {{ orderDetail.purchaseQuantity }}</p>
                                        </div>
                                        <div class="quantity-price">
                                            <p class="price">Ціна: {{ goods.price * orderDetail.purchaseQuantity }} USD</p>
                                        </div>
                                    </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function() {
            $('.order-block').click(function() {
                var orderBlock = $(this);
                var orderDetails = orderBlock.find('.order-details');
                var toggleArrow = orderBlock.find('.toggle-arrow');

                orderDetails.slideToggle();

                toggleArrow.toggleClass('fa-chevron-up fa-chevron-down');
            });
        });
    </script>
{% endblock %}

{% block footer %}
    {% include 'footer.html.twig' %}
{% endblock %}

templates/quicStats.html.twig
<span class="cart-quantity" id="goods-quick-stats">{{ cartQuantity() }}</span>

templates/reviews.stream.html.twig
<turbo-stream action="update" target="goods-quick-stats">
    <template>
        {% include 'quicStats.html.twig' %}
    </template>
</turbo-stream>

<turbo-stream action="replace" target="goods-quick-stats2">
    <template>
        {% include '_cart.html.twig' %}
    </template>
</turbo-stream>

<turbo-stream action="replace" target="success-turbo">
    <template>
        {% for message in app.flashes('success') %}
            <script>document.body.style.overflow = 'hidden';</script>
            <div class="success-yes-goods" onclick="this.remove(); document.body.style.overflow = 'auto';">
                <div class="success-popup">
                    <div class="success-icon">
                        <i class='bx bx-check-circle'></i>
                    </div>
                    <h5 class="yep">Успіх!</h5>
                    <div class="success-message">{{ message }}</div>
                    <div class="end-success-message">Закрити</div>
                </div>
            </div>
        {% endfor %}
    </template>
</turbo-stream>

templates/success_order.html.twig
{% extends 'base.html.twig' %}

{% block header %}
    {% include 'header.html.twig' %}
{% endblock %}

{% block body %}
    <div class="success-page">
        <div class="success-icon"><i class='bx bx-package'></i></div>
        <h1 class="title-success-order">Замовлення успішно оформлене</h1>
        <p class="ty-order">Дякуємо за ваше замовлення! Ось деталі вашого замовлення:</p>
        <div class="order-details-success">
            <div class="order-success-info">
                <span>Номер замовлення: № {{ order.orderNumber }}</span>
            </div>
            <div class="order-success-info">
                <span>Ім'я: John Doe</span>
            </div>
            <div class="order-success-info">
                <span>Телефон: 123-456-7890</span>
            </div>
            <div class="order-success-info">
                <span>Email: johndoe@example.com</span>
            </div>
            <div class="order-items">
                <table>
                    <thead>
                    <tr>
                        <th>Товар</th>
                        <th>Кількість</th>
                        <th>Розмір</th>
                    </tr>
                    </thead>
                    {% for orderDetail in order.orderDetails %}
                        <tbody>
                        {% set goods = orderDetail.goodsId %}
                        <tr class="detail-success">
                            <td> <div class="product-name"><p>{{ goods.name }}</p></div>
                                <img class="product-image" src="{{ goods.image }}" alt="{{ goods.name }}">
                            </td>
                            <td>{{ orderDetail.purchaseQuantity }}</td>
                            <td>{{ orderDetail.size}}</td>
                        </tr>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
        </div>
        <div class="total-amount-success">
            <span>Загальна сума замовлення:</span>
            <span> {{ order.totalAmount}} USD</span>
        </div>
        <p class="p-success">{{ order.orderDate|date('d F Y H:i') }}</p>
        <p class="p-success">Кількість товарів в замовленні: {{  order.totalQuantity }}</p>

    </div>
{% endblock %}

{% block footer %}
    {% include 'footer.html.twig' %}
{% endblock %}